# CircleCI configuraton file

version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
    - image: "cimg/base:latest"
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD # project secret
    steps:
      - run: echo "say hello to YAML!"
