name: 'Terraform Destroy Workflow'
on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm.'
        required: true

jobs:
  terraform_destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy'
    permissions:
      contents: read
      packages: write
      id-token: write
      issues: write
      pull-requests: write
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure
    steps:
    - name: Checkout
      uses: actions/checkout@v3        

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.ACTION_ROLE }} 
        aws-region: ${{ secrets.REGION }}
        role-session-name: GitHub-OIDC-TERRAFORM   

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init Destroy PRD
      if: github.ref_name == 'main'
      id: init_prod
      env:
        AWS_BUCKET_NAME: ${{ secrets.PROD_STATE_BUCKET }}
        AWS_BUCKET_KEY_NAME: ${{ secrets.STATE_BUCKET_KEY }}
      run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

    - name: Terraform Init Destroy UAT
      if: github.ref_name == 'staging'
      id: init_uat
      env:
        AWS_BUCKET_NAME: ${{ secrets.UAT_STATE_BUCKET }}
        AWS_BUCKET_KEY_NAME: ${{ secrets.STATE_BUCKET_KEY }}
      run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

    - name: Terraform Init Destroy NPE
      if: github.ref_name == 'develop'
      id: init
      env:
        AWS_BUCKET_NAME: ${{ secrets.NPE_STATE_BUCKET }}
        AWS_BUCKET_KEY_NAME: ${{ secrets.STATE_BUCKET_KEY }}
      run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"

    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
