name: "Terraform action"
on:
  push:
    branches:
      - develop
      - main
  pull_request:
permissions:
      id-token: write # This is required for aws oidc connection
      contents: read # This is required for actions/checkout
      pull-requests: write # This is required for gh bot to comment PR
env:
  TF_LOG: DEBUG
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
  
    - name: Package Lambda function
      run: zip -r function.zip .

    - name: Configure AWS credentials from AWS account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ACTION_ROLE }}
        aws-region: ${{ secrets.REGION }}

    - name: Deploy to S3
      run: aws s3 cp function.zip s3://${{ vars.FUNCTION_BUCKET }}/npe/function.zip
    
    - name: Pass source code path
      id: pass_path
      run: |
          echo "filepath=$(echo ${{ vars.FUNCTION_BUCKET }})" >> $GITHUB_ENV

    - name: Set the tag
      id: set_tag
      run: echo "::set-output name=filepath::$filepath"
    outputs:
        filepath: ${{ steps.set_tag.outputs.filepath }}
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      packages: write
      id-token: write
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure
    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.3

      - name: Configure AWS credentials from AWS account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ACTION_ROLE }}
          aws-region: ${{ secrets.REGION }}
          role-session-name: GitHub-OIDC-TERRAFORM
          

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check 
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init 

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          terraform apply -auto-approve -input=false
          echo "============================== API ENDPOINT BELOW ==================================="
          terraform output api_endpoint
          echo "============================== API ENDPOINT ABOVE ==================================="